import { CakeProfitStats } from "backend-feature/calculateCakeProfitFromPool";
import { fetcher } from "backend-feature/utils/fetcher";
import AsciiTable from "ascii-table";
import type { NextPage } from "next";
import Head from "next/head";
import useSWR from "swr";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const { data, error } = useSWR<CakeProfitStats, any>(
    "/api/getSelfCakeStats",
    fetcher
  );
  const asciiTable = data.outputResponses.reduce((acc, el) => {
    return acc.addRow(el);
  },
  new AsciiTable());
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {asciiTable.toString()}
      </div>
    </div>
  );
};

export default Home;
